### ISSUE TITLE
Great Work!

### ISSUE THREAD

**Issue by Arcitec** [fujiawei-dev/ffmpeg-generator#1]
Hi Fujiawei.

The work you are doing with this ffmpeg-python rewrite looks great!

To make it popular you should edit your pypi project page to put a "Project Homepage" link to this repo:

https://pypi.org/project/ffmpeg-generator/#description

Because I had to do a lot of Google searching manually to find your GitHub profile and your repo. ;-)

**Comment by fujiawei-dev** [comment]
This is my negligence. It has been added now.
