### ISSUE TITLE
关于GL转场滤镜的请教

### ISSUE THREAD

**Issue by rdaim** [fujiawei-dev/ffmpeg-generator#8]
关于GL转场滤镜的请教，这里机器上装的FFMPEG应该是要集成GL模块编译后才能用吗？谢谢，辛苦了！

**Comment by fujiawei-dev** [comment]
是的，可以参考 [Dockerfile ](https://github.com/fujiawei-dev/ffmpeg-generator/blob/master/docker/ffmpeg/gltransition.Dockerfile)里的编译过程。

**Comment by fujiawei-dev** [comment]
题外话，推荐自带的 xfade 和 blend 实现转场，GL 除 Linux 平台之外编译十分困难。

**Comment by rdaim** [comment]
好的，非常感谢。FF可惜没把GL这么好的转场效果直接集成进去。你的作品很棒！

**Comment by rdaim** [comment]
对 了，还想请教一下，python库中，有好一点的支持文本（文字）动画的开源库推荐一下不？类似像 animation.css 这种效果的。

**Comment by fujiawei-dev** [comment]
[manim](https://github.com/3b1b/manim)

https://docs.manim.org.cn/getting_started/example_scenes.html#textexample

**Comment by rdaim** [comment]
这个库太过于庞大，而且面向数学方向的，似乎并不太适合文本动画效果

**Comment by rdaim** [comment]
动画效果也少，有类似像GL这种封装好的，效果又多，支持直接方法调用的为最好，不然还得自己写。哈哈哈哈

**Comment by fujiawei-dev** [comment]
估计没有这样的
